# https://travis-ci.org/dirvine/wwww
language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq clang-3.5 clang++-3.5 libstdc++-4.9-dev; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.5" CC="clang-3.5"; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
after_install:
  - mkdir build
  - cd build
  - cmake ../
branches:
  only:
    - master
    - coverity

# https://scan.coverity.com/projects/4280
env:
  global:
  - secure: "HxsvTIjLQox6r/BATsRx0X5WADORNuqVFifTDFYcJTPCw2kTrMA7g4uQSdKUoez3SlCU3DdszjAe3JcQC7qZ5DRpMZw7CaKgtCXSDzN9F6pxBbeXdiPXvk2EI7SPhg1nznrlLIihye5hVV0ZLf4zz3BfV2KTDa6UbD5GArJsU+Y="
addons:
  coverity_scan:
    project:
      name: "dirvine/wwww"
    notification_email: david.irvine@maidsafe.net
    build_command_prepend: "cov-configure --template --comptype gcc --compiler $CC &&
    mkdir build && cd build && cmake ../"
    build_command: "cd build && make"
    branch_pattern: coverity

script:
  - "make" 
