# https://travis-ci.org/datagraph/librdf
language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.9-dev; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++" CC="clang"; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - mkdir build
  - cd build
  - cmake ../
script:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then cmake ../  && make && make check; fi
branches:
  only:
    - master
    - coverity

# https://scan.coverity.com/projects/4280
env:
  global:
  - secure: "qrUoVTt4f_MFP8wKmwyNMA"
addons:
  coverity_scan:
    project:
      name: dirvine/wwww
    notification_email: david.irvine@maidsafe.net
    build_command_prepend: cov-configure --comptype gcc --compiler $CC && cmake ../
    build_command: make
    branch_pattern: coverity
